export const ROLES = Object.freeze({
  TEACHER: "teacher",
  STUDENT: "student",
});

export const WS_EVENTS = Object.freeze({
  START_SESSION: "START_SESSION",
  END_SESSION: "END_SESSION",
  MARK_ATTENDANCE: "MARK_ATTENDANCE",
  SESSION_STARTED: "SESSION_STARTED",
  SESSION_ENDED: "SESSION_ENDED",
  ATTENDANCE_UPDATED: "ATTENDANCE_UPDATED",
  ERROR: "ERROR",
});

export const HTTP_STATUS = Object.freeze({
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  SERVER_ERROR: 500,
});
