export const ROLES = Object.freeze({
  TEACHER: "teacher",
  STUDENT: "student",
});

export const WS_EVENTS = Object.freeze({
  START_SESSION: "START_SESSION",
  END_SESSION: "END_SESSION",
  MARK_ATTENDANCE: "MARK_ATTENDANCE",
  SESSION_STARTED: "SESSION_STARTED",
  SESSION_ENDED: "SESSION_ENDED",
  ATTENDANCE_UPDATED: "ATTENDANCE_UPDATED",
  ERROR: "ERROR",
});
